[pytest]
pythonpath =
    .
    train_station_app

addopts =
    --tb=short
    -v
    -s

testpaths = test

# collect files that don't follow test_*.py naming
python_files = test_*.py *_testing.py senaries.py

markers =
    slow:       marks tests as slow
    smoke:      quick sanity checks
    crud:       full CRUD tests
    functional: HTTP endpoint tests
    scenario:   end-to-end workflow tests
    negative:   error / edge-case tests
